version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_install:
      - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH pip install ".[docs]"

sphinx:
  configuration: docs/conf.py