[tool.poetry]
name = "nuance"
version = "0.6.1"
description = "Transit signals detection among correlated noises"
authors = ["Lionel Garcia"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
tinygp = "*"
jax = "^0.4.25"
jaxlib = "*"
jaxopt = "*"
numpy = "*"
matplotlib = "*"
scipy = "*"
multiprocess = "*"
tqdm = "*"

[tool.poetry.group.dev.dependencies]
pytest = "*"
black = "*"

[tool.poetry.group.test.dependencies]
pytest = "*"
astropy = "*"

[tool.poetry.group.docs.dependencies]
sphinx = "*"
docutils = "*"
jupyterlab = "*"
myst-parser = "*"
sphinx-book-theme = ">=1.1.0"
myst-nb = "*"
sphinx-copybutton = "*"
sphinx-design = "*"
toml = "*"
ipywidgets = "*"
wotan = "*"
astropy = "*"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
