name: Build, test and publish

on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v5
        name: Install Python
        with:
          python-version: "3.10"
      - name: Build sdist and wheel
        run: |
          python -m pip install -U pip
          python -m pip install -U build
          python -m build .
      - uses: actions/upload-artifact@v4
        with:
          path: dist/*

  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: python -m pip install -U pip
      - name: Install package and test dependencies
        run: python -m pip install ".[dev]"
      - name: Run tests
        run: python -m pytest

  publish:
    environment:
      name: pypi
      url: https://pypi.org/p/portrait
    permissions:
      id-token: write
    needs: [test]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: artifact
          path: dist
      - uses: pypa/gh-action-pypi-publish@v1.8.14